// <auto-generated />
namespace BTL_THU_VIEN_NHOM_18.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class lienket : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lienket));
        
        string IMigrationMetadata.Id
        {
            get { return "202011131138200_lienket"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
